In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [19]:
stu_details = {'sid': [1, 2,3, 4, 5], 'sname': ['a', 'b', 'c', 'd', 'e'], 'sregion': ['n', 's', 'c', 'd', 'e']}

In [4]:
stu_details

{'sid': [1, 2, 3, 4, 5],
 'sanme': ['a', 'b', 'c', 'd', 'e'],
 'sregion': ['n', 's', 'c', 'd', 'e']}

In [5]:
df = pd.DataFrame(stu_details)

In [6]:
df

   sid sanme sregion
0    1     a       n
1    2     b       s
2    3     c       c
3    4     d       d
4    5     e       e

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
import numpy as np

In [14]:
arrTest = pd.DataFrame(np.array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), columns =['id', 'name', 'age', 'test'])

In [15]:
arrTest

   id  name  age  test
0   1     2    3     4
1   5     6    7     8
2   9    10   11    12

In [22]:
df.sanme

0    a
1    b
2    c
3    d
4    e
Name: sanme, dtype: object

In [23]:
df.sregion

0    n
1    s
2    c
3    d
4    e
Name: sregion, dtype: object

In [26]:
df[['sanme', 'sregion']]

  sanme sregion
0     a       n
1     b       s
2     c       c
3     d       d
4     e       e

In [27]:
df.iloc[:]

   sid sanme sregion
0    1     a       n
1    2     b       s
2    3     c       c
3    4     d       d
4    5     e       e

In [30]:
df.iloc[::]

   sid sanme sregion
0    1     a       n
1    2     b       s
2    3     c       c
3    4     d       d
4    5     e       e

In [31]:
df.iloc[0:3,:]

   sid sanme sregion
0    1     a       n
1    2     b       s
2    3     c       c

In [32]:
df.iloc[0:3,1:]

  sanme sregion
0     a       n
1     b       s
2     c       c

In [33]:
df.iloc[[0, 2, 4], [0, 2]]

   sid sregion
0    1       n
2    3       c
4    5       e

In [35]:
df.iloc[[0, 2, 4], [0, 2]].values # gives in array

array([[1, 'n'],
       [3, 'c'],
       [5, 'e']], dtype=object)